trigger:
  branches:
    include:
      - master

jobs:
- job: MemoryLeakDetection
  displayName: 'Build and Test C++ Application'
  steps:
  - task: ShellScript@2
    inputs:
      scriptPath: memory_leak_detection.sh
    displayName: 'Check for memory leaks using Valgrind'
