trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: ShellScript@2
    inputs:
      scriptPath: memory_leak_detection.sh
    displayName: 'Check for memory leaks using Valgrind'
